package com.formula.manager.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a racing car used by a team.
 * Each team has exactly 2 cars.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "cars")
public class Car {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Model name of the car (e.g. "RB20").
     */
    @Column(nullable = false)
    private String model;

    /**
     * Engine/motor type used in the car (e.g. "Honda RBPT").
     */
    @Column(nullable = false)
    private String motor;

    /**
     * Year the car model was manufactured.
     */
    @Column(nullable = false)
    private int year;

    /**
     * Horsepower of the car engine.
     */
    @Column(nullable = false)
    private int horsePower;

    /**
     * Weight of the car in kilograms.
     */
    @Column(nullable = false)
    private double weight;

    /**
     * Team this car belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "team_id", nullable = false)
    private Team team;
}gi