package com.formula.manager.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
 * Represents a Formula Championship.
 * Championship is the root entity — all seasons belong to a championship.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "championships")
public class Championship {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the championship (e.g. "Formula 1 World Championship").
     */
    @Column(nullable = false)
    private String name;

    /**
     * Type of the championship (e.g. "Formula 1", "Formula 2").
     */
    @Column(nullable = false)
    private String type;

    /**
     * Year in which the championship takes place.
     */
    @Column(nullable = false)
    private int year;

    /**
     * Total prize money awarded in this championship.
     */
    @Column(nullable = false)
    private double prizeMoney;

    /**
     * Name of the organization that organizes the championship.
     */
    @Column(nullable = false)
    private String organizer;

    /**
     * List of seasons belonging to this championship.
     * Seasons cannot exist without a championship (weak entity).
     */
    @OneToMany(mappedBy = "championship", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Season> seasons;
}