package com.formula.manager.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
 * Represents a Formula Championship.
 * Championship is the root entity — all seasons belong to a championship.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "championships")
public class Championship {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the championship (e.g. "Formula 1 World Championship").
     * Invalid values: null, empty string, whitespace-only string,
     * string shorter than 3 or longer than 100 characters.
     */
    @NotBlank(message = "Championship name cannot be blank")
    @Size(min = 3, max = 100, message = "Championship name must be between 3 and 100 characters")
    @Column(nullable = false)
    private String name;

    /**
     * Type of the championship (e.g. "Formula 1", "Formula 2").
     * Invalid values: null, empty string, whitespace-only string.
     */
    @NotBlank(message = "Championship type cannot be blank")
    @Column(nullable = false)
    private String type;

    /**
     * Year in which the championship takes place.
     * Invalid values: any value less than 1950.
     */
    @Min(value = 1950, message = "Championship year cannot be before 1950")
    @Column(nullable = false)
    private int year;

    /**
     * Total prize money awarded in this championship.
     * Invalid values: negative values.
     */
    @PositiveOrZero(message = "Prize money cannot be negative")
    @Column(nullable = false)
    private double prizeMoney;

    /**
     * Name of the organization that organizes the championship.
     * Invalid values: null, empty string, whitespace-only string.
     */
    @NotBlank(message = "Organizer cannot be blank")
    @Column(nullable = false)
    private String organizer;

    /**
     * List of seasons belonging to this championship.
     * Seasons cannot exist without a championship (weak entity).
     */
    @OneToMany(mappedBy = "championship", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Season> seasons;
}