package com.formula.manager.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a racing circuit where races are held.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "circuits")
public class Circuit {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the circuit (e.g. "Monza").
     */
    @Column(nullable = false)
    private String name;

    /**
     * Country where the circuit is located.
     */
    @Column(nullable = false)
    private String country;

    /**
     * Length of the circuit in kilometers.
     */
    @Column(nullable = false)
    private double length;

    /**
     * Number of turns on the circuit.
     */
    @Column(nullable = false)
    private int numberOfTurns;

    /**
     * Maximum spectator capacity of the circuit.
     */
    @Column(nullable = false)
    private int capacity;
}