package com.formula.manager.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * Represents a racing driver participating in the championship.
 * A driver belongs to exactly one team.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "drivers")
public class Driver {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * First name of the driver.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Last name of the driver.
     */
    @Column(nullable = false)
    private String surname;

    /**
     * Nationality of the driver (e.g. "Dutch").
     */
    @Column(nullable = false)
    private String nationality;

    /**
     * Total championship points accumulated by the driver.
     */
    @Column(nullable = false)
    private int points;

    /**
     * Date of birth of the driver.
     */
    @Column(nullable = false)
    private LocalDate dateOfBirth;

    /**
     * Total number of championships won by the driver.
     */
    @Column(nullable = false)
    private int numberOfChampionships;

    /**
     * Team this driver belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "team_id", nullable = false)
    private Team team;

    /**
     * List of race results for this driver.
     */
    @OneToMany(mappedBy = "driver", cascade = CascadeType.ALL)
    private List<RaceResult> raceResults;
}