package com.formula.manager.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * Represents a racing driver participating in the championship.
 * A driver belongs to exactly one team.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "drivers")
public class Driver {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * First name of the driver.
     * Invalid values: null, empty string, whitespace-only string,
     * string shorter than 2 or longer than 50 characters.
     */
    @NotBlank(message = "Driver name cannot be blank")
    @Size(min = 2, max = 50, message = "Driver name must be between 2 and 50 characters")
    @Column(nullable = false)
    private String name;

    /**
     * Last name of the driver.
     * Invalid values: null, empty string, whitespace-only string,
     * string shorter than 2 or longer than 50 characters.
     */
    @NotBlank(message = "Driver surname cannot be blank")
    @Size(min = 2, max = 50, message = "Driver surname must be between 2 and 50 characters")
    @Column(nullable = false)
    private String surname;

    /**
     * Nationality of the driver (e.g. "Dutch").
     * Invalid values: null, empty string, whitespace-only string.
     */
    @NotBlank(message = "Nationality cannot be blank")
    @Column(nullable = false)
    private String nationality;

    /**
     * Total championship points accumulated by the driver.
     * Invalid values: negative values.
     */
    @PositiveOrZero(message = "Points cannot be negative")
    @Column(nullable = false)
    private int points;

    /**
     * Date of birth of the driver.
     * Invalid values: null, any date that is today or in the future.
     */
    @NotNull(message = "Date of birth cannot be null")
    @Past(message = "Date of birth must be in the past")
    @Column(nullable = false)
    private LocalDate dateOfBirth;

    /**
     * Total number of championships won by the driver.
     * Invalid values: negative values.
     */
    @PositiveOrZero(message = "Number of championships cannot be negative")
    @Column(nullable = false)
    private int numberOfChampionships;

    /**
     * Team this driver belongs to.
     * Invalid values: null.
     */
    @NotNull(message = "Team cannot be null")
    @ManyToOne
    @JoinColumn(name = "team_id", nullable = false)
    private Team team;

    /**
     * List of race results for this driver.
     */
    @OneToMany(mappedBy = "driver", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<RaceResult> raceResults;
}