package com.formula.manager.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the result of a driver in a specific race.
 * Acts as an associative class between Driver and Race (many-to-many).
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "race_results")
public class RaceResult {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Final position of the driver in the race (e.g. 1 for first place).
     * Invalid values: zero and negative values.
     */
    @Positive(message = "Position must be positive")
    @Column(nullable = false)
    private int position;

    /**
     * Total race time of the driver (e.g. "1:30:25.456").
     * Invalid values: null, empty string, whitespace-only string.
     */
    @NotBlank(message = "Time cannot be blank")
    @Column(nullable = false)
    private String time;

    /**
     * Championship points earned by the driver in this race.
     * Invalid values: negative values.
     */
    @PositiveOrZero(message = "Points cannot be negative")
    @Column(nullable = false)
    private int points;

    /**
     * Driver who achieved this result.
     * Invalid values: null.
     */
    @NotNull(message = "Driver cannot be null")
    @ManyToOne
    @JoinColumn(name = "driver_id", nullable = false)
    private Driver driver;

    /**
     * Race in which this result was achieved.
     * Invalid values: null.
     */
    @NotNull(message = "Race cannot be null")
    @ManyToOne
    @JoinColumn(name = "race_id", nullable = false)
    private Race race;
}