package com.formula.manager.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * Represents a race within a season.
 * Race is a weak entity — it cannot exist without a Season.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "races")
public class Race {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the race (e.g. "Monaco Grand Prix").
     * Invalid values: null, empty string, whitespace-only string,
     * string shorter than 3 or longer than 100 characters.
     */
    @NotBlank(message = "Race name cannot be blank")
    @Size(min = 3, max = 100, message = "Race name must be between 3 and 100 characters")
    @Column(nullable = false)
    private String name;

    /**
     * Date when the race begins.
     * Invalid values: null.
     */
    @NotNull(message = "Date of beginning cannot be null")
    @Column(nullable = false)
    private LocalDate dateOfBeginning;

    /**
     * Date when the race ends.
     * Invalid values: null.
     */
    @NotNull(message = "Date of ending cannot be null")
    @Column(nullable = false)
    private LocalDate dateOfEnding;

    /**
     * Total number of laps in the race.
     * Invalid values: zero and negative values.
     */
    @Positive(message = "Number of laps must be positive")
    @Column(nullable = false)
    private int numberOfLaps;

    /**
     * Season this race belongs to.
     * Invalid values: null.
     */
    @NotNull(message = "Season cannot be null")
    @ManyToOne
    @JoinColumn(name = "season_id", nullable = false)
    private Season season;

    /**
     * Circuit on which this race is held.
     * Invalid values: null.
     */
    @NotNull(message = "Circuit cannot be null")
    @ManyToOne
    @JoinColumn(name = "circuit_id", nullable = false)
    private Circuit circuit;

    /**
     * List of results for this race.
     */
    @OneToMany(mappedBy = "race", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<RaceResult> raceResults;
}