package com.formula.manager.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * Represents a race within a season.
 * Race is a weak entity — it cannot exist without a Season.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "races")
public class Race {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the race (e.g. "Monaco Grand Prix").
     */
    @Column(nullable = false)
    private String name;

    /**
     * Date when the race begins.
     */
    @Column(nullable = false)
    private LocalDate dateOfBeginning;

    /**
     * Date when the race ends.
     */
    @Column(nullable = false)
    private LocalDate dateOfEnding;

    /**
     * Total number of laps in the race.
     */
    @Column(nullable = false)
    private int numberOfLaps;

    /**
     * Season this race belongs to.
     */
    @ManyToOne
    @JoinColumn(name = "season_id", nullable = false)
    private Season season;

    /**
     * Circuit on which this race is held.
     */
    @ManyToOne
    @JoinColumn(name = "circuit_id", nullable = false)
    private Circuit circuit;

    /**
     * List of results for this race.
     */
    @OneToMany(mappedBy = "race", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<RaceResult> raceResults;
}