package com.formula.manager.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.List;

/**
 * Represents a season within a championship.
 * Season is a weak entity — it cannot exist without a Championship.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "seasons")
public class Season {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Year in which the season takes place.
     */
    @Min(value = 1950, message = "Season year cannot be before 1950")
    @Column(nullable = false)
    private int year;

    /**
     * Total number of races in this season.
     */
    @Positive(message = "Number of races must be positive")
    @Column(nullable = false)
    private int numberOfRaces;

    /**
     * Indicates whether the season is currently active.
     */
    @Column(nullable = false)
    private boolean active;

    /**
     * Start date of the season.
     */
    @NotNull(message = "Start time cannot be null")
    @Column(nullable = false)
    private LocalDate startTime;

    /**
     * Championship this season belongs to.
     */
    @NotNull(message = "Championship cannot be null")
    @ManyToOne
    @JoinColumn(name = "championship_id", nullable = false)
    private Championship championship;

    /**
     * List of races in this season.
     * Races cannot exist without a season (weak entity).
     */
    @OneToMany(mappedBy = "season", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Race> races;
}