package com.formula.manager.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
 * Represents a racing team participating in the championship.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "teams")
public class Team {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the team (e.g. "Red Bull Racing").
     * Invalid values: null, empty string, whitespace-only string,
     * string shorter than 3 or longer than 100 characters.
     */
    @NotBlank(message = "Team name cannot be blank")
    @Size(min = 3, max = 100, message = "Team name must be between 3 and 100 characters")
    @Column(nullable = false)
    private String name;

    /**
     * Country the team represents.
     * Invalid values: null, empty string, whitespace-only string.
     */
    @NotBlank(message = "Country cannot be blank")
    @Column(nullable = false)
    private String country;

    /**
     * Annual budget of the team in millions.
     * Invalid values: negative values.
     */
    @PositiveOrZero(message = "Budget cannot be negative")
    @Column(nullable = false)
    private double budget;

    /**
     * Name of the team principal.
     * Invalid values: null, empty string, whitespace-only string.
     */
    @NotBlank(message = "Team principal cannot be blank")
    @Column(nullable = false)
    private String teamPrincipal;

    /**
     * Year the team was founded.
     * Invalid values: any value less than 1950.
     */
    @Min(value = 1950, message = "Year of forming cannot be before 1950")
    @Column(nullable = false)
    private int yearOfForming;

    /**
     * List of drivers in this team (max 3).
     */
    @OneToMany(mappedBy = "team",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.EAGER)
    private List<Driver> drivers;

    /**
     * List of cars used by this team (max 2).
     */
    @OneToMany(mappedBy = "team", cascade = CascadeType.ALL)
    private List<Car> cars;
}