package com.formula.manager.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
 * Represents a racing team participating in the championship.
 *
 * @author kPlavsic
 * @version 1.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "teams")
public class Team {

    /**
     * Unique identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the team (e.g. "Red Bull Racing").
     */
    @Column(nullable = false)
    private String name;

    /**
     * Country the team represents.
     */
    @Column(nullable = false)
    private String country;

    /**
     * Annual budget of the team in millions.
     */
    @Column(nullable = false)
    private double budget;

    /**
     * Name of the team principal.
     */
    @Column(nullable = false)
    private String teamPrincipal;

    /**
     * Year the team was founded.
     */
    @Column(nullable = false)
    private int yearOfForming;

    /**
     * List of drivers in this team (max 3).
     */
    @OneToMany(mappedBy = "team", cascade = CascadeType.ALL)
    private List<Driver> drivers;

    /**
     * List of cars used by this team (max 2).
     */
    @OneToMany(mappedBy = "team", cascade = CascadeType.ALL)
    private List<Car> cars;
}